version: '3.8'

networks:
    dockerapi-dev:
        driver: bridge

services:
    redis:
        image: "redis:alpine"
        hostname: redis
        ports:
        - "6379:6379"
    # default API
    runner-api:
        image: redisapi:latest
        container_name: runner
        #platform: linux/amd64
        depends_on: [redis]
        ports:
            - '5088:80'
        networks:
            - dockerapi-dev
volumes:
    postgres:
